import type { Metadata } from "next";
import "./globals.css";
import './satoshi.css'
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import SEO from "@/components/seo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full max-w-[1800px] mx-auto flex flex-col min-h-screen bg-[#001408] h-full  fw-regular antialiased relative`}
      >
          <div className="absolute top-0 left-0 -z-10 w-full h-screen overflow-hidden">
            <img src="./hero.jpg" alt="hero backdrop " className=" opacity-[0.08] mask-b" />
          </div>
               <SEO/>

     <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
